### ISSUE TITLE
Release vaadin-crud-flow

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-crud-flow#1]
### Project Setup
- [x] GitHub repo
- [x] Skeleton structure (component, IT, vaadin-com demo, TB elements)
- [x] Maven setup (vaadin-parent, Bower & Webjar, TB tests, etc)
- [x] Build setup (Travis, TC snapshot & release builds, release checklist)

### Web Component Integration
- [x] Crud component binding to `vaadin-crud`
- [x] Append server-side grid and editor to the WC
- [x] Receive events for new, edit, save and delete
- [x] Control editor closing from the server-side

### CrudGrid (extends Grid)
- [x] Provide constructor to enable/disable the default grid filtering
- [x] Provide a built-in filter type (CrudFilter)
- [x] Manage data provider
- [x] Hook filter into data provider
- [x] Hook sorting into data provider

### Integration tests
- [x] Validate events
- [x] Validate component with custom grid
- [x] Validate custom search implementation (Bakery case study)

### TestBench Elements
- [x] Extract elements from integration tests

### VaadinCom
- [x] Documentation
- [x] Prepare assets for VaadinCom and Directory (e.g screenshot, description)
- [x] Advanced demo with custom grid
- [x]  Integrate demos with VaadinCom
